# Generated by Django 4.2.7 on 2025-09-03 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('vuelo', 'Vuelo'), ('hotel', 'Hotel'), ('paquete', 'Paquete Vuelo + Hotel')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=10)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('detalles', models.JSONField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('codigo_reserva', models.CharField(max_length=20, unique=True)),
                ('travelpayouts_id', models.CharField(blank=True, max_length=100, null=True)),
                ('travelpayouts_link', models.URLField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('documento_identidad', models.CharField(max_length=50)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros', to='core.reserva')),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=12)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('id_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.reserva')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
