# Generated by Django 4.2.7 on 2025-09-03 20:11

import apps.hoteles.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('destino', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('adultos', models.PositiveSmallIntegerField(default=2)),
                ('ninos', models.PositiveSmallIntegerField(default=0)),
                ('habitaciones', models.PositiveSmallIntegerField(default=1)),
                ('precio_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('categoria_max', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resultados', models.JSONField(blank=True, null=True)),
                ('total_resultados', models.PositiveIntegerField(default=0)),
                ('api_utilizada', models.CharField(default='travelpayouts', max_length=50)),
                ('api_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Búsqueda de Hotel',
                'verbose_name_plural': 'Búsquedas de Hoteles',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='HabitacionTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_adultos', models.PositiveSmallIntegerField(default=2)),
                ('capacidad_ninos', models.PositiveSmallIntegerField(default=0)),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiene_balcon', models.BooleanField(default=False)),
                ('tiene_vista', models.BooleanField(default=False)),
                ('tiene_caja_fuerte', models.BooleanField(default=False)),
                ('tiene_minibar', models.BooleanField(default=False)),
                ('tiene_aire_acondicionado', models.BooleanField(default=True)),
                ('tiene_calefaccion', models.BooleanField(default=True)),
                ('tiene_television', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('categoria', models.PositiveSmallIntegerField(help_text='Categoría del hotel (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tiene_piscina', models.BooleanField(default=False)),
                ('tiene_spa', models.BooleanField(default=False)),
                ('tiene_gimnasio', models.BooleanField(default=False)),
                ('tiene_wifi', models.BooleanField(default=False)),
                ('tiene_estacionamiento', models.BooleanField(default=False)),
                ('admite_mascotas', models.BooleanField(default=False)),
                ('check_in', models.TimeField(default='14:00')),
                ('check_out', models.TimeField(default='12:00')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HotelImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('imagen', models.ImageField(upload_to='hoteles/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('es_principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Imagen de Hotel',
                'verbose_name_plural': 'Imágenes de Hoteles',
            },
        ),
        migrations.CreateModel(
            name='HotelServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('disponible', models.BooleanField(default=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Servicio de Hotel Específico',
                'verbose_name_plural': 'Servicios de Hoteles Específicos',
            },
        ),
        migrations.CreateModel(
            name='ServicioHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio de Hotel',
                'verbose_name_plural': 'Servicios de Hoteles',
            },
        ),
        migrations.CreateModel(
            name='TarifaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('disponible', models.BooleanField(default=True)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cargos_adicionales', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('habitacion_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='hoteles.habitaciontipo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='hoteles.hotel')),
            ],
            options={
                'verbose_name': 'Tarifa de Habitación',
                'verbose_name_plural': 'Tarifas de Habitaciones',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo_reserva', models.CharField(default=apps.hoteles.models.generar_codigo_reserva, max_length=12, unique=True)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('noches', models.PositiveIntegerField(default=1)),
                ('adultos', models.PositiveSmallIntegerField(default=2)),
                ('ninos', models.PositiveSmallIntegerField(default=0)),
                ('habitaciones', models.PositiveSmallIntegerField(default=1)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_huesped', models.CharField(max_length=200)),
                ('email_huesped', models.EmailField(max_length=254)),
                ('telefono_huesped', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('habitacion_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hoteles.habitaciontipo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hoteles.hotel')),
                ('servicios_adicionales', models.ManyToManyField(blank=True, to='hoteles.serviciohotel')),
            ],
            options={
                'verbose_name': 'Reserva de Hotel',
                'verbose_name_plural': 'Reservas de Hoteles',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
