# Generated by Django 4.2.7 on 2025-09-03 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservahotel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_hotel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelservicio',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='hoteles.hotel'),
        ),
        migrations.AddField(
            model_name='hotelservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.serviciohotel'),
        ),
        migrations.AddField(
            model_name='hotelimagen',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='hoteles.hotel'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hoteles.hotel'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='hoteles.habitaciontipo'),
        ),
        migrations.AddField(
            model_name='busquedahotel',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='hoteles.serviciohotel'),
        ),
        migrations.AddField(
            model_name='busquedahotel',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hotelservicio',
            unique_together={('hotel', 'servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('hotel', 'numero')},
        ),
    ]
