# Generated by Django 4.2.7 on 2025-09-03 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iata', models.CharField(max_length=2, unique=True)),
                ('codigo_icao', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Aerolínea',
                'verbose_name_plural': 'Aerolíneas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('codigo_icao', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'ordering': ['ciudad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='BusquedaVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_ida', models.DateField()),
                ('fecha_vuelta', models.DateField(blank=True, null=True)),
                ('pasajeros_adultos', models.IntegerField(default=1)),
                ('pasajeros_ninos', models.IntegerField(default=0)),
                ('pasajeros_bebes', models.IntegerField(default=0)),
                ('clase', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20)),
                ('precio_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resultados', models.JSONField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas_destino', to='vuelos.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas_origen', to='vuelos.aeropuerto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas_vuelos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Búsqueda de Vuelo',
                'verbose_name_plural': 'Búsquedas de Vuelos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_vuelo', models.CharField(max_length=10)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('duracion', models.DurationField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asientos_disponibles', models.IntegerField(default=0)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='vuelos.aerolinea')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_llegada', to='vuelos.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_salida', to='vuelos.aeropuerto')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['fecha_salida'],
                'unique_together': {('aerolinea', 'numero_vuelo', 'fecha_salida')},
            },
        ),
    ]
